FROM python:3-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY requirements.txt /code/

RUN apt-get update && apt-get install -y build-essential

RUN pip install wheel
RUN pip install -r requirements.txt

COPY . /code/
